echo ""
echo "                    ______"
echo "                 _-' .   .\`-_"
echo "             |/ /  .. . '   .\ \|"
echo "            |/ /         .  ..\ \|"
echo "          \|/ |: .   ._|_ .: . | \|/"
echo "           \/ |   _|_. |.. .:  | \/"
echo "           \||| . .| .: _|_   .|||/"
echo "          \__| \ :. :.  .|.  ./ |__/"
echo "            __| \_  .    .. _/ |__"
echo "             __|  \`-______-'  |__"
echo "                -,____  ____,-"
echo "                  ---'  '---"
echo ""
echo "         UNITED FEDERATION OF PLANETS"
echo ""
echo ""
